default: &default
  adapter: postgresql 
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["db_username"] %>
  password: <%= ENV["db_password"] %>

development:
  <<: *default
  database: hitched_development

  test:
    <<: *default
    database: hitched_test
